@base_url=http://localhost:8080

###
GET {{base_url}}

###
GET {{base_url}}/partners

###
POST {{base_url}}/partners
Content-Type: application/json

{
    "name": "Partner teste 01" 
}

###
@partner_id = b3957c7b-c5f2-47c5-a6c0-49a21d3a92d8

###
GET {{base_url}}/customers

###
POST {{base_url}}/customers
Content-Type: application/json

{
    "name": "Customer 1",
    "cpf": "592.110.870-74"
}

###
@customer_id = f355408f-3978-4724-9f57-3fd90061af74

###
GET {{base_url}}/events

###
POST {{base_url}}/events
Content-Type: application/json

{
    "name": "Event 1",
    "description": "Description 1",
    "date": "2020-01-01T00:00:00.000Z",
    "partner_id": "{{partner_id}}"
}

###
@event_id = 35d984d3-9187-447b-9a70-46d99f91e35e

###
GET {{base_url}}/events/{{event_id}}/sections

###
POST {{base_url}}/events/{{event_id}}/sections
Content-Type: application/json

{
    "name": "Section 1",
    "description": "Description 1",
    "total_spots": 1,
    "price": 200
}

###
PUT {{base_url}}/events/{{event_id}}/publish-all

###
@section_id = 808e0d0f-f944-44f5-86ce-80fe44898675

###
PUT {{base_url}}/events/{{event_id}}/sections/{{section_id}}
Content-Type: application/json

{
    "name": "Section 2 updateddddd",
    "description": "Description 2 updatedddd"
}

###
GET {{base_url}}/events/{{event_id}}/sections/{{section_id}}/spots

@spot_id = 13be8e1a-7ab6-4f7b-b95d-a9c9bd904256

###
PUT {{base_url}}/events/{{event_id}}/sections/{{section_id}}/spots/{{spot_id}}
Content-Type: application/json

{
    "location": "Location 1 updated"
}

###
GET {{base_url}}/events/{{event_id}}/orders

###
POST {{base_url}}/events/{{event_id}}/orders
Content-Type: application/json

{
    "customer_id": "{{customer_id}}",
    "section_id": "{{section_id}}",
    "spot_id": "{{spot_id}}",
    "card_token": "tok_visa"
}