@base_url=http://localhost:8080

###
GET {{base_url}}

###
GET {{base_url}}/partners

###
POST {{base_url}}/partners
Content-Type: application/json

{
    "name": "Partner 10"
}

###
@partner_id = cb303e84-2ba0-4cfa-b88d-6921985d7933

###
GET {{base_url}}/customers

###
POST {{base_url}}/customers
Content-Type: application/json

{
    "name": "Customer 1",
    "cpf": "592.110.870-74"
}

###
@customer_id = 61f0ff6e-0bb1-4635-8899-4b88ce46975b

###
GET {{base_url}}/events

###
POST {{base_url}}/events
Content-Type: application/json

{
    "name": "Event 1",
    "description": "Description 1",
    "date": "2020-01-01T00:00:00.000Z",
    "partner_id": "{{partner_id}}"
}

###
@event_id = 3181cb03-59e6-469a-9942-358b07882a72

###
GET {{base_url}}/events/{{event_id}}/sections

###
POST {{base_url}}/events/{{event_id}}/sections
Content-Type: application/json

{
    "name": "Section 1",
    "description": "Description 1",
    "total_spots": 1,
    "price": 200
}

###
PUT {{base_url}}/events/{{event_id}}/publish-all

###
@section_id = 42a5f5b1-30c5-4b2f-b9b8-84e5cc948542

###
PUT {{base_url}}/events/{{event_id}}/sections/{{section_id}}
Content-Type: application/json

{
    "name": "Section 1 updateddddd",
    "description": "Description 1 updatedddd"
}

###
GET {{base_url}}/events/{{event_id}}/sections/{{section_id}}/spots

###
PUT {{base_url}}/events/{{event_id}}/sections/{{section_id}}/spots/2179f4e2-b3bc-4be9-b55d-f0876f24987d
Content-Type: application/json

{
    "location": "Location 1 updated"
}

###
GET {{base_url}}/events/{{event_id}}/orders

###
POST {{base_url}}/events/{{event_id}}/orders
Content-Type: application/json

{
    "customer_id": "{{customer_id}}",
    "section_id": "{{section_id}}",
    "spot_id": "96298e63-5a38-4352-b97d-322259f10921",
    "card_token": "tok_visa"
}